package top.sharehome.javaee.bean;

public class Address {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.address_id
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    private Integer addressId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.address_provice
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    private String addressProvice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_address.address_city
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    private String addressCity;

    public Address() {
    }

    public Address(Integer addressId, String addressProvice, String addressCity) {
        this.addressId = addressId;
        this.addressProvice = addressProvice;
        this.addressCity = addressCity;
    }

    @Override
    public String toString() {
        return getClass().getName() + "{" +
                "addressId=" + addressId +
                ", addressProvice='" + addressProvice + '\'' +
                ", addressCity='" + addressCity + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.address_id
     *
     * @return the value of t_address.address_id
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public Integer getAddressId() {
        return addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.address_id
     *
     * @param addressId the value for t_address.address_id
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public void setAddressId(Integer addressId) {
        this.addressId = addressId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.address_provice
     *
     * @return the value of t_address.address_provice
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public String getAddressProvice() {
        return addressProvice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.address_provice
     *
     * @param addressProvice the value for t_address.address_provice
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public void setAddressProvice(String addressProvice) {
        this.addressProvice = addressProvice == null ? null : addressProvice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_address.address_city
     *
     * @return the value of t_address.address_city
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public String getAddressCity() {
        return addressCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_address.address_city
     *
     * @param addressCity the value for t_address.address_city
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity == null ? null : addressCity.trim();
    }
}