package top.sharehome.javaee.bean;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_id
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_account
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    private String adminAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_admin.admin_password
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    private String adminPassword;

    public Admin() {
    }

    public Admin(Integer adminId, String adminAccount, String adminPassword) {
        this.adminId = adminId;
        this.adminAccount = adminAccount;
        this.adminPassword = adminPassword;
    }

    @Override
    public String toString() {
        return getClass().getName() + "{" +
                "adminId=" + adminId +
                ", adminAccount='" + adminAccount + '\'' +
                ", adminPassword='" + adminPassword + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_id
     *
     * @return the value of t_admin.admin_id
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_id
     *
     * @param adminId the value for t_admin.admin_id
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_account
     *
     * @return the value of t_admin.admin_account
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public String getAdminAccount() {
        return adminAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_account
     *
     * @param adminAccount the value for t_admin.admin_account
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public void setAdminAccount(String adminAccount) {
        this.adminAccount = adminAccount == null ? null : adminAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_admin.admin_password
     *
     * @return the value of t_admin.admin_password
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public String getAdminPassword() {
        return adminPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_admin.admin_password
     *
     * @param adminPassword the value for t_admin.admin_password
     *
     * @mbg.generated Sat Nov 05 18:10:11 CST 2022
     */
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword == null ? null : adminPassword.trim();
    }
}