package top.sharehome.javaee.bean;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_one
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    private Integer studentOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_id
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    private String studentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_name
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    private String studentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_gender
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    private String studentGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_birthday
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    private String studentBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_college
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    private String studentCollege;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_major
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    private String studentMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_grade
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    private String studentGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_phone
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    private String studentPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_student.student_address
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    private String studentAddress;

    public Student() {
    }

    public Student(Integer studentOne, String studentId, String studentName, String studentGender, String studentBirthday, String studentCollege, String studentMajor, String studentGrade, String studentPhone, String studentAddress) {
        this.studentOne = studentOne;
        this.studentId = studentId;
        this.studentName = studentName;
        this.studentGender = studentGender;
        this.studentBirthday = studentBirthday;
        this.studentCollege = studentCollege;
        this.studentMajor = studentMajor;
        this.studentGrade = studentGrade;
        this.studentPhone = studentPhone;
        this.studentAddress = studentAddress;
    }

    @Override
    public String toString() {
        return getClass().getName() + "{" +
                "studentOne=" + studentOne +
                ", studentId='" + studentId + '\'' +
                ", studentName='" + studentName + '\'' +
                ", studentGender='" + studentGender + '\'' +
                ", studentBirthday='" + studentBirthday + '\'' +
                ", studentCollege='" + studentCollege + '\'' +
                ", studentMajor='" + studentMajor + '\'' +
                ", studentGrade='" + studentGrade + '\'' +
                ", studentPhone='" + studentPhone + '\'' +
                ", studentAddress='" + studentAddress + '\'' +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_one
     *
     * @return the value of t_student.student_one
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public Integer getStudentOne() {
        return studentOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_one
     *
     * @param studentOne the value for t_student.student_one
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public void setStudentOne(Integer studentOne) {
        this.studentOne = studentOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_id
     *
     * @return the value of t_student.student_id
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public String getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_id
     *
     * @param studentId the value for t_student.student_id
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public void setStudentId(String studentId) {
        this.studentId = studentId == null ? null : studentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_name
     *
     * @return the value of t_student.student_name
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_name
     *
     * @param studentName the value for t_student.student_name
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_gender
     *
     * @return the value of t_student.student_gender
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public String getStudentGender() {
        return studentGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_gender
     *
     * @param studentGender the value for t_student.student_gender
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public void setStudentGender(String studentGender) {
        this.studentGender = studentGender == null ? null : studentGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_birthday
     *
     * @return the value of t_student.student_birthday
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public String getStudentBirthday() {
        return studentBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_birthday
     *
     * @param studentBirthday the value for t_student.student_birthday
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public void setStudentBirthday(String studentBirthday) {
        this.studentBirthday = studentBirthday == null ? null : studentBirthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_college
     *
     * @return the value of t_student.student_college
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public String getStudentCollege() {
        return studentCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_college
     *
     * @param studentCollege the value for t_student.student_college
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public void setStudentCollege(String studentCollege) {
        this.studentCollege = studentCollege == null ? null : studentCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_major
     *
     * @return the value of t_student.student_major
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public String getStudentMajor() {
        return studentMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_major
     *
     * @param studentMajor the value for t_student.student_major
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public void setStudentMajor(String studentMajor) {
        this.studentMajor = studentMajor == null ? null : studentMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_grade
     *
     * @return the value of t_student.student_grade
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public String getStudentGrade() {
        return studentGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_grade
     *
     * @param studentGrade the value for t_student.student_grade
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public void setStudentGrade(String studentGrade) {
        this.studentGrade = studentGrade == null ? null : studentGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_phone
     *
     * @return the value of t_student.student_phone
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public String getStudentPhone() {
        return studentPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_phone
     *
     * @param studentPhone the value for t_student.student_phone
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public void setStudentPhone(String studentPhone) {
        this.studentPhone = studentPhone == null ? null : studentPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_student.student_address
     *
     * @return the value of t_student.student_address
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public String getStudentAddress() {
        return studentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_student.student_address
     *
     * @param studentAddress the value for t_student.student_address
     *
     * @mbggenerated Sun Nov 06 13:55:40 CST 2022
     */
    public void setStudentAddress(String studentAddress) {
        this.studentAddress = studentAddress == null ? null : studentAddress.trim();
    }
}